BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no

UNICODE_ENABLE = no

AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
ENCODER_ENABLE = no
MIDI_ENABLE = no
OLED_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
